baseURL = 'https://otoliver.ink/'
languageCode = 'zh-CN'
title = 'OtoLiver'
theme = 'lotusdocs'

[markup.goldmark.renderer]
    unsafe = true

[[menu.primary]]
    name  = "Docs"
    url = "/docs/"
    identifier = "docs"
    weight = 10
